# Generated by Django 4.2.6 on 2023-10-16 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(default=None,blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.size'),
            preserve_default=False,
        ),
    ]
