# Generated by Django 4.2.6 on 2023-11-19 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ordereditems',
        ),
    ]
