# Generated by Django 4.2.6 on 2023-11-19 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_delete_ordereditems'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordereditems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField(null=True)),
                ('coupon_applied', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='user.cartitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
