# Generated by Django 4.2.6 on 2023-10-16 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_size_cart_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
