# Generated by Django 4.2.6 on 2023-11-28 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_ordereditems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditems',
            name='coupon_applied',
        ),
    ]
