# Generated by Django 4.2.6 on 2023-11-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_ordereditems_coupon_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='coupon_applied',
            field=models.BooleanField(default=False),
        ),
    ]
