# Generated by Django 4.2.6 on 2023-10-16 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_size_product_size'),
        ('user', '0004_size_usercart_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('products', models.ManyToManyField(to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usercart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='usercart',
            name='size',
        ),
        migrations.RemoveField(
            model_name='usercart',
            name='user',
        ),
        migrations.DeleteModel(
            name='size',
        ),
        migrations.DeleteModel(
            name='usercart',
        ),
    ]
