# Generated by Django 4.2.6 on 2023-10-16 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_size_product_size'),
        ('user', '0006_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.size'),
        ),
    ]
