# Generated by Django 4.2.6 on 2023-10-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_cart_quantity_alter_cart_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
