# Generated by Django 4.2.6 on 2023-10-18 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_product_price'),
        ('user', '0022_alter_cartitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.size'),
        ),
    ]
