# Generated by Django 4.2.6 on 2023-10-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_cartitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
