# Generated by Django 4.2.6 on 2023-10-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_district_alter_address_pin_state_alter_address_state'),
        ('user', '0025_alter_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.ManyToManyField(to='checkout.address'),
        ),
    ]
