# Generated by Django 4.2.6 on 2023-10-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_cart_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='address',
        ),
    ]
