# Generated by Django 4.2.6 on 2023-10-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
