# Generated by Django 4.2.6 on 2023-10-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_remove_order_items_remove_order_user_delete_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default=1, max_length=50),
        ),
    ]
