# Generated by Django 4.2.6 on 2023-10-25 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_cartitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Cancel', 'Cancel'), ('Return', 'Return')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.item_status'),
        ),
    ]
