# Generated by Django 4.2.6 on 2023-10-25 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_item_status_alter_cartitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='status',
        ),
    ]
