# Generated by Django 4.2.6 on 2023-10-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_alter_cartitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_status',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Cancel', 'Cancel'), ('Return', 'Return'), ('Delivered', 'Delivered')], max_length=10),
        ),
    ]
