# Generated by Django 4.2.6 on 2023-10-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_alter_item_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_status',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return', 'Returned')], max_length=10),
        ),
    ]
