# Generated by Django 4.2.6 on 2023-10-21 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='pin',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Kerala', 'Kerala'), ('Tamil nadu', 'Tamil Nadu'), ('Karnataka', 'Karnataka'), ('Maharashtra', 'Maharashtra')], max_length=50)),
                ('districts', models.ManyToManyField(to='checkout.district')),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.state'),
        ),
    ]
