# Generated by Django 4.2.6 on 2023-10-21 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_district_alter_address_pin_state_alter_address_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='distrcit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='checkout.district'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='district',
            name='district',
            field=models.CharField(choices=[('Kasaragod', 'Kasaragod'), ('Kannur', 'Kannur'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Thrissur', 'Thrissur'), ('Ernankulam', 'Kochi'), ('Alapuzha', 'Alapuzha'), ('Kottayam', 'Kottayam'), ('Kollam', 'Kollam'), ('Palakkad', 'Palakkad'), ('Trivandrum', 'Trivandrum')], max_length=20),
        ),
        migrations.DeleteModel(
            name='state',
        ),
    ]
