# Generated by Django 4.2.6 on 2023-10-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_address_state_address_distrcit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='distrcit',
        ),
        migrations.DeleteModel(
            name='district',
        ),
    ]
