# Generated by Django 4.2.6 on 2023-10-21 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_remove_address_distrcit_delete_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('Kasaragod', 'Kasaragod'), ('Kannur', 'Kannur'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Thrissur', 'Thrissur'), ('Ernankulam', 'Kochi'), ('Alapuzha', 'Alapuzha'), ('Kottayam', 'Kottayam'), ('Kollam', 'Kollam'), ('Palakkad', 'Palakkad'), ('Trivandrum', 'Trivandrum')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='distrcit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='checkout.district'),
            preserve_default=False,
        ),
    ]
