# Generated by Django 4.2.6 on 2023-10-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_district_address_distrcit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='distrcit',
            new_name='district',
        ),
    ]
