# Generated by Django 4.2.6 on 2023-11-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_wallet_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.BigIntegerField(),
        ),
    ]
