# Generated by Django 4.2.6 on 2023-10-21 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_remove_cart_address'),
        ('checkout', '0006_rename_distrcit_address_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.cart'),
        ),
    ]
