# Generated by Django 4.2.6 on 2023-10-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_payment_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment',
            new_name='payment_method',
        ),
    ]
