# Generated by Django 4.2.6 on 2023-12-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_ordereditems_total'),
        ('checkout', '0009_alter_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='user.ordereditems'),
        ),
    ]
