# Generated by Django 4.2.6 on 2023-10-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_rename_payment_payment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(choices=[('UPI', 'UPI'), ('COD', 'COD')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='payment',
        ),
    ]
