# Generated by Django 4.2.6 on 2023-12-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_remove_order_items_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='money',
            field=models.BigIntegerField(default=0),
        ),
    ]
