# Generated by Django 4.2.6 on 2023-10-24 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_remove_order_items_remove_order_user_delete_payment_and_more'),
        ('checkout', '0011_order_address_order_payment_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.cart'),
            preserve_default=False,
        ),
    ]
