# Generated by Django 4.2.6 on 2023-10-24 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_remove_order_items_remove_order_user_delete_payment_and_more'),
        ('checkout', '0013_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.cart'),
        ),
    ]
