# Generated by Django 4.2.6 on 2023-12-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_alter_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
