# Generated by Django 4.2.6 on 2023-12-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_coupon_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupon',
            name='coupon',
            field=models.CharField(max_length=50),
        ),
    ]
