# Generated by Django 4.2.6 on 2023-12-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0018_alter_order_order_status_alter_order_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='district',
        ),
    ]
