# Generated by Django 4.2.6 on 2023-10-25 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0019_remove_order_items_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='cart',
        ),
    ]
