# Generated by Django 4.2.6 on 2023-10-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0021_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
    ]
