# Generated by Django 4.2.6 on 2023-10-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0022_remove_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processing', 'processing'), ('shipped', 'shipped'), ('delivered', 'delivered')], max_length=20)),
            ],
        ),
    ]
