# Generated by Django 4.2.6 on 2023-10-25 12:17

import checkout.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0023_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default=1, max_length=10, verbose_name=checkout.models.order_status),
        ),
    ]
