# Generated by Django 4.2.6 on 2023-10-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0025_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_status',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
    ]
