# Generated by Django 4.2.6 on 2023-10-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0027_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_status',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
    ]
