# Generated by Django 4.2.6 on 2023-10-26 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0028_alter_order_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='checkout.order_status'),
        ),
    ]
