# Generated by Django 4.2.6 on 2023-10-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customuser_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
