# Generated by Django 4.2.6 on 2023-10-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_img3_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img2',
        ),
        migrations.AddField(
            model_name='product',
            name='frontimg',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='rearimg',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
