# Generated by Django 4.2.6 on 2023-10-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_product_img1_remove_product_img2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='frontimg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rearimg',
        ),
    ]
