# Generated by Django 4.2.6 on 2023-10-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_product_frontimg_remove_product_rearimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='frontimg',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='rearimg',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
