# Generated by Django 4.2.6 on 2023-10-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_product_frontimg_product_rearimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.IntegerField(null='not in stock'),
            preserve_default='not in stock',
        ),
    ]
