# Generated by Django 4.2.6 on 2023-11-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='quantity_sold',
            new_name='order_quantity',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='total_sales',
            new_name='total_sales_amt',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='date',
        ),
    ]
