# Generated by Django 4.2.6 on 2023-11-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_quantity_sold_sales_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_created_at',
            field=models.DateField(null=True),
        ),
    ]
