# Generated by Django 4.2.6 on 2023-11-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_customuser_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='disc_price',
            field=models.IntegerField(default=0, verbose_name='discount price'),
        ),
    ]
