# Generated by Django 4.2.6 on 2023-11-19 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quantity',
        ),
    ]
