# Generated by Django 4.2.6 on 2023-11-27 04:29

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_delete_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_cropping',
            field=image_cropping.fields.ImageRatioField('img', '120x120', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropping'),
        ),
    ]
