# Generated by Django 4.2.6 on 2023-11-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_category_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='valid_to',
            field=models.DateField(null=True),
        ),
    ]
