# Generated by Django 4.2.6 on 2023-11-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_category_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
    ]
