# Generated by Django 4.2.6 on 2023-12-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_category_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='price_increment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
