# Generated by Django 4.2.6 on 2023-12-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_size_price_increment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_cropping',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
