# Generated by Django 4.2.6 on 2023-12-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_product_image_cropping_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='frontimg',
            field=models.ImageField(max_length=500, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(max_length=500, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rearimg',
            field=models.ImageField(max_length=500, null=True, upload_to='pics'),
        ),
    ]
