# Generated by Django 4.2.6 on 2023-12-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_delete_sales_brand_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='gender',
        ),
    ]
