# Generated by Django 4.2.6 on 2023-12-08 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_product_gender_delete_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='arrival_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
